/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;

import java.awt.Component;
import Controller.Discount;


/**
 *
 * @author Home
 */
public class AddDiscount extends javax.swing.JFrame {

    private final String day[] = {"friday", "saturday"};
    private Component AddADiscount;
    Discount discountObj = new Discount();

    /**
     * Creates new form AddADiscount
     */
    public AddDiscount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDay = new javax.swing.JTextField();
        jTextFieldDiscount = new javax.swing.JTextField();
        jButtonAddDis = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonReset = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Discount");
        setMinimumSize(new java.awt.Dimension(525, 350));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Day of Discount");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(47, 95, 110, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Discount");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(47, 205, 110, 16);

        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("Note: Can only add on Weekends");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(47, 131, 260, 16);
        getContentPane().add(jTextFieldDay);
        jTextFieldDay.setBounds(198, 93, 150, 32);
        getContentPane().add(jTextFieldDiscount);
        jTextFieldDiscount.setBounds(198, 198, 150, 29);

        jButtonAddDis.setText("Add Discount");
        jButtonAddDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddDisActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAddDis);
        jButtonAddDis.setBounds(330, 260, 110, 30);

        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack);
        jButtonBack.setBounds(10, 0, 50, 30);

        jLabel4.setFont(new java.awt.Font("Vani", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Add a Discount");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 20, 130, 40);

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReset);
        jButtonReset.setBounds(240, 260, 80, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-6, 0, 510, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddDisActionPerformed
        // TODO add your handling code here:
        try {
            String offerday = jTextFieldDay.getText();
            double DiscountValue = Double.parseDouble(jTextFieldDiscount.getText());
            discountObj.setOfferday(offerday);

            if (offerday.equalsIgnoreCase(day[0]) || offerday.equalsIgnoreCase(day[1])) {
                discountObj.setdiscount(DiscountValue);
                discountObj.AddDiscount(DiscountValue, offerday);

                JOptionPane.showMessageDialog(AddADiscount,
                        "Discount has been added Successfully.",
                        "Success",
                        JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(AddADiscount,
                        "You can only set Discount on Weekends.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(AddADiscount,
                    "Invalid Input",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;}
    }//GEN-LAST:event_jButtonAddDisActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
         new AdministrativeModule().setVisible(true);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        jTextFieldDay.setText("");
        jTextFieldDiscount.setText("");
    }//GEN-LAST:event_jButtonResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDiscount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDiscount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDiscount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDiscount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDiscount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddDis;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldDay;
    private javax.swing.JTextField jTextFieldDiscount;
    // End of variables declaration//GEN-END:variables
}
