/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 * import static GUI.CancelOrderJFrame.drive; import static
 * GUI.CancelOrderJFrame.name; import static GUI.CancelOrderJFrame.password;
 * import static GUI.CancelOrderJFrame.url; import java.awt.Component; import
 * java.sql.Connection; import java.sql.DriverManager; import
 * java.sql.PreparedStatement; import java.sql.ResultSet; import
 * java.sql.Statement; import javax.swing.JOptionPane; import
 * javax.swing.JTextField; import resturant.managment.system.Bill; import resturant.managment.system.customer;*
 */
import static View.CancelOrderJFrame.drive;
import static View.CancelOrderJFrame.name;
import static View.CancelOrderJFrame.password;
import static View.CancelOrderJFrame.url;
import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import Controller.Bill;
import Controller.Discount;
import Controller.customer;
import Model.Database;

/**
 *
 * @author silkroad
 */
public class billJFrame extends javax.swing.JFrame {

    /**
     * Creates new form billJFrame
     */
    /**
     * Connection con = null; static final String drive =
     * "com.mysql.cj.jdbc.Driver"; static final String url =
     * "jdbc:mysql://localhost/restaurant"; static final String name = "Amira";
     * static final String password = "02468"; private double totalCost; private
     * double totalBill; private final double tax; private final double tip;
     * private double taxAmount; private double tipAmount; private String order;
     * private int quantity;
     */
    Connection con = null;
    static final String drive = "com.mysql.cj.jdbc.Driver";
    static final String url = "jdbc:mysql://localhost/project";
    static final String name = "omnia";
    static final String password = "Omnia123";
    private double totalCost;
    private double totalBill;
    private double BillAfterDiscount = 0;
    private double Discount;

    private final double tax;
    private final double tip;
    private double taxAmount;
    private double tipAmount;
    private String order;
    private int quantity;

    public billJFrame() {
        initComponents();
        billHeader();
        this.tax = 0.0675;
        this.tip = 0.2;
    }

    private void billHeader() {
        jTextArea.setText("============================" + "\n" + "Resturant Name"
                + "\n" + "Contact No-xxxxxxxx" + "\n" + "Address- enter address" + "\n"
                + "============================" + "\n");
    }

    private void printAtTextArea() {
        jTextArea.setText(jTextArea.getText() + jTextFieldOrderValue.getText() + "-" + jTextFieldQuantityValue.getText() + "\t\t" + jTextFieldPriceValue.getText() + "\n" + "total= " + getTotalBill());
    }

    private void printAtTextAreaDiscount() {
        jTextArea.setText(jTextArea.getText() + jTextFieldOrderValue.getText() + "-" + jTextFieldQuantityValue.getText() + "\t\t" + jTextFieldPriceValue.getText() + "\n" + "total= " + getTotalBill() + "\nTotal Bill After Discount = " + getBillAfterDiscount());
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabelTitel = new javax.swing.JLabel();
        jTextFieldOrderValue = new javax.swing.JTextField();
        jLabelOrder = new javax.swing.JLabel();
        jTextFieldQuantityValue = new javax.swing.JTextField();
        jLabelQuantity = new javax.swing.JLabel();
        jTextFieldPriceValue = new javax.swing.JTextField();
        jButtonReset = new javax.swing.JButton();
        jButtonAddOrder = new javax.swing.JButton();
        jLabelPrice = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jButtonCancelOrder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jCheckBoxDiscount = new javax.swing.JCheckBox();
        jLabelDay = new javax.swing.JLabel();
        jTextFieldDay = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldcustomerId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculate Bill");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitel.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitel.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabelTitel.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitel.setText("Billing ");
        jLabelTitel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabelTitel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 122, 49));

        jTextFieldOrderValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOrderValueActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldOrderValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 100, 25));

        jLabelOrder.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelOrder.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOrder.setText("Order");
        jLabelOrder.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabelOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 66, -1));

        jTextFieldQuantityValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuantityValueActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldQuantityValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 100, 25));

        jLabelQuantity.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelQuantity.setForeground(new java.awt.Color(255, 255, 255));
        jLabelQuantity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQuantity.setText("Quantity");
        jLabelQuantity.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabelQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 66, -1));

        jTextFieldPriceValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPriceValueActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPriceValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 100, 25));

        jButtonReset.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 90, -1));

        jButtonAddOrder.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButtonAddOrder.setText("Add");
        jButtonAddOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddOrderActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAddOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 90, -1));

        jLabelPrice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPrice.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPrice.setText("Price");
        jLabelPrice.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabelPrice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 66, -1));

        jButtonExit.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 90, -1));

        jButtonCancelOrder.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButtonCancelOrder.setText("Cancel");
        jButtonCancelOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelOrderActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 90, -1));

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 238, 290));

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton2.setText("<-- Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setText("search");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMaximumSize(new java.awt.Dimension(71, 25));
        jButton1.setMinimumSize(new java.awt.Dimension(71, 25));
        jButton1.setPreferredSize(new java.awt.Dimension(71, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 90, -1));

        jCheckBoxDiscount.setBackground(new java.awt.Color(102, 102, 102));
        jCheckBoxDiscount.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jCheckBoxDiscount.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxDiscount.setText("Add Discount");
        jCheckBoxDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDiscountActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 100, -1));

        jLabelDay.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDay.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDay.setText("Current Day ");
        getContentPane().add(jLabelDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 80, -1));
        getContentPane().add(jTextFieldDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 100, 25));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Customer ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        getContentPane().add(jTextFieldcustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 100, 25));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/gold-cutlery-set-black-background_1220-4095.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPriceValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPriceValueActionPerformed
        // TODO add your handling code here:
        Bill bill = new Bill();
        if (jTextFieldPriceValue.getText().equals(bill.getCost())) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_jTextFieldPriceValueActionPerformed

    private void jButtonCancelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelOrderActionPerformed
        // TODO add your handling code here:
        Bill bill = new Bill();
        this.setVisible(false);
        new CancelOrderJFrame().setVisible(true);
    }//GEN-LAST:event_jButtonCancelOrderActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        Bill bill = new Bill();
        try {
            bill.iExitSystem();
        } catch (NumberFormatException e) {
            JOptionPane.showConfirmDialog(null, "Billing Error");
        }
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        jTextFieldOrderValue.setText("");
        jTextFieldPriceValue.setText("");
        jTextFieldQuantityValue.setText("");
        jTextArea.setText("");
        jTextFieldDay.setText("");
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonAddOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddOrderActionPerformed
        // TODO add your handling code here:
        /*String order = jTextFieldOrderValue.getText();
        int quantity = Integer.parseInt(jTextFieldQuantityValue.getText());
        double price=Double.parseDouble(jTextFieldPriceValue.getText());
        printAtTextArea();*/
        try {
            String order = jTextFieldOrderValue.getText();
            if(jTextFieldOrderValue.getText().equals("")){
                 JOptionPane.showMessageDialog(rootPane, "Error Input");
                 return;
             }
            int quantity = Integer.parseInt(jTextFieldQuantityValue.getText());
            double price = Double.parseDouble(jTextFieldPriceValue.getText());
            String Day = jTextFieldDay.getText();
            if(jTextFieldDay.getText().equals("")){
                 JOptionPane.showMessageDialog(rootPane, "Error Input");
                 return;
             }
            Discount Disc = new Discount();
            Database database = new Database();
            database.RetrieveDiscount(Disc);

           
        if (jCheckBoxDiscount.isSelected()) {
            if (jTextFieldDay.getText().equals(Disc.getOfferday())) {
                printAtTextAreaDiscount();
                totalBill=BillAfterDiscount;
            } else {
                JOptionPane.showMessageDialog(this, "Offer isn't applied to " + jTextFieldDay.getText() + "s");
                printAtTextArea();
            }
        
        
        }
        else{
        printAtTextArea();
        }
        
            Bill bill = new Bill();
            try {
//                Class.forName(drive);
//                con = DriverManager.getConnection(url, "root", "");
//                if (con != null) {
//                    System.out.println("connected");
//                }
//                String query = "INSERT INTO billing (Day,FoodOrder,Quantity,TotalCost,TaxAmount,TipAmount,TotalBill) VALUES ('" + Day + "','" + order + "','" + quantity + "','" + totalCost + "','" + taxAmount + "','" + tipAmount + "','" + totalBill + "')";
//                PreparedStatement pst = con.prepareStatement(query);
//                pst.execute();
//                String q = "UPDATE customer SET Payments=" + totalBill + " WHERE id= " + Integer.parseInt(jTextFieldcustomerId.getText()) + "";
//                
//            pst.executeUpdate(q);
//                JOptionPane.showMessageDialog(rootPane, "Add Success");
              /*   Class.forName(drive);
            con = DriverManager.getConnection(url, name, password);
            if (con != null) {
                System.out.println("connected");
            }
            stmt = con.createStatement();
            String q = "UPDATE registration SET Rewards=" + rewards + " WHERE Email= \"" + email + " \"";
            stmt.executeUpdate(q);

            stmt.close();
            con.close();*/

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }
            jTextFieldOrderValue.setText("");
            jTextFieldPriceValue.setText("");
            jTextFieldQuantityValue.setText("");
            jTextFieldDay.setText("");
            jTextFieldcustomerId.setText("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Error Input");
            return;
        }

    }//GEN-LAST:event_jButtonAddOrderActionPerformed

    public double getTotalBill() {
        int quantity = Integer.parseInt(jTextFieldQuantityValue.getText());
        double price = Double.parseDouble(jTextFieldPriceValue.getText());

        taxAmount = tax * price;
        totalCost += (price * quantity) + taxAmount;
        tipAmount = tip * totalCost;
        totalBill = tipAmount + totalCost;
        return totalBill;
    }

    public double getBillAfterDiscount() {
        Discount Disc = new Discount();
        Database database = new Database();

        database.RetrieveDiscount(Disc);
        Discount = totalBill * (Disc.getdiscount() / 100);
        BillAfterDiscount = totalBill - Discount;
        return BillAfterDiscount;

    }


    private void jTextFieldQuantityValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuantityValueActionPerformed
        // TODO add your handling code here:
        Bill bill = new Bill();
        if (jTextFieldQuantityValue.getText().equals(bill.getQuantity())) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_jTextFieldQuantityValueActionPerformed

    private void jTextFieldOrderValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOrderValueActionPerformed
        // TODO add your handling code here:
        Bill bill = new Bill();
        if (jTextFieldOrderValue.getText().equals(bill.getOrder())) {
            this.setVisible(false);
        }
        /*int checkid = 0;
        String Name = jTextFieldOrderValue.getText();
       // bill c = new customer();
        try {
            Connection con = customer.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from meals where Name='" + Name + "'");
            while (rs.next()) {
                checkid = 1;
                jTextFieldPriceValue.setText(rs.getString(2));
            }
            if (checkid == 0) {
                JOptionPane.showMessageDialog(null, "meal's name does not Exist");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }*/
    }//GEN-LAST:event_jTextFieldOrderValueActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new EmployeeModule().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        int checkid = 0;
//        String Name = jTextFieldOrderValue.getText();
//        Connection con = null;
//        Statement stmt = null;
//        try {
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            
//            con = DriverManager.getConnection("jdbc:mysql://localhost/restaurant", "omnia", "Omnia123");
//            stmt = con.createStatement();
//            ResultSet rs = stmt.executeQuery("select *from meals where Name='" + Name + "'");
//            while (rs.next()) {
//                checkid = 1;
//                jTextFieldOrderValue.setEditable(false);
//                jTextFieldPriceValue.setText(rs.getString(3));
//
//            }
//            if (checkid == 0) {
//                JOptionPane.showMessageDialog(null, "Meals Name does not Exist");
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
//        }
//        
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBoxDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxDiscountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAddOrder;
    private javax.swing.JButton jButtonCancelOrder;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JCheckBox jCheckBoxDiscount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelDay;
    private javax.swing.JLabel jLabelOrder;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelQuantity;
    private javax.swing.JLabel jLabelTitel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextField jTextFieldDay;
    private javax.swing.JTextField jTextFieldOrderValue;
    private javax.swing.JTextField jTextFieldPriceValue;
    private javax.swing.JTextField jTextFieldQuantityValue;
    private javax.swing.JTextField jTextFieldcustomerId;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
