/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;
import Controller.GUIManager;
import Controller.InvoiceOfficer;
import Model.Database;

/**
 *
 * @author silkroad
 */
public class Billing extends javax.swing.JFrame {
Database database = new Database();
    /**
     * Creates new form Billing
     */
    public Billing() {
        initComponents();
        billHeader();
    }
     private void billHeader() {
        jTextArea1.setText("============================" + "\n" + "Resturant Name"
                + "\n" + "Contact No-xxxxxxxx" + "\n" + "Address- enter address" + "\n"
                + "============================" + "\n");
    }

    private void printAtTextArea() {
        int quantity = Integer.parseInt(jTextFieldquantity.getText());
        double price = Double.parseDouble(jTextFieldprice.getText());
        InvoiceOfficer invoice = new InvoiceOfficer();
        jTextArea1.setText(jTextArea1.getText() + jTextFieldOrder.getText() + "-" + jTextFieldquantity.getText() + "\t\t" + jTextFieldprice.getText() + "\n" + "total= " + invoice.CalculateBill(quantity, price));
      //  database.saveOrder(order,quantity,TotalCost,TaxAmount,TipAmount,TotalBill);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabeltitle = new javax.swing.JLabel();
        jTextFieldOrder = new javax.swing.JTextField();
        jLabelorder = new javax.swing.JLabel();
        jTextFieldquantity = new javax.swing.JTextField();
        jLabelquantity = new javax.swing.JLabel();
        jTextFieldprice = new javax.swing.JTextField();
        jLabelprice = new javax.swing.JLabel();
        jTextFieldDay = new javax.swing.JTextField();
        jLabelDay = new javax.swing.JLabel();
        jButtonSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonReset = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jLabelbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Billing");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabeltitle.setBackground(new java.awt.Color(255, 255, 255));
        jLabeltitle.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabeltitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabeltitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeltitle.setText("Billing ");
        jLabeltitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabeltitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 122, 49));

        jTextFieldOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOrderActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 100, 25));

        jLabelorder.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelorder.setForeground(new java.awt.Color(255, 255, 255));
        jLabelorder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelorder.setText("Order");
        jLabelorder.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabelorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 66, -1));

        jTextFieldquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldquantityActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 100, 25));

        jLabelquantity.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelquantity.setForeground(new java.awt.Color(255, 255, 255));
        jLabelquantity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelquantity.setText("Quantity");
        jLabelquantity.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabelquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 66, -1));

        jTextFieldprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldpriceActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 100, 25));

        jLabelprice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelprice.setForeground(new java.awt.Color(255, 255, 255));
        jLabelprice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelprice.setText("Price");
        jLabelprice.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabelprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 66, -1));
        getContentPane().add(jTextFieldDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 100, 25));

        jLabelDay.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelDay.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay.setText("Current Day");
        jLabelDay.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabelDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 80, -1));

        jButtonSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSearch.setText("Search");
        jButtonSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSearch.setMaximumSize(new java.awt.Dimension(71, 25));
        jButtonSearch.setMinimumSize(new java.awt.Dimension(71, 25));
        jButtonSearch.setPreferredSize(new java.awt.Dimension(71, 25));
        getContentPane().add(jButtonSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 90, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 238, 290));

        jButtonReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 90, -1));

        jButtonExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonExit.setText("Exit");
        jButtonExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonExit.setPreferredSize(new java.awt.Dimension(71, 25));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 90, -1));

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCancel.setMaximumSize(new java.awt.Dimension(71, 25));
        jButtonCancel.setMinimumSize(new java.awt.Dimension(71, 25));
        jButtonCancel.setPreferredSize(new java.awt.Dimension(71, 25));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 90, -1));

        jButtonAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAdd.setText("Add");
        jButtonAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAdd.setMaximumSize(new java.awt.Dimension(71, 25));
        jButtonAdd.setMinimumSize(new java.awt.Dimension(71, 25));
        jButtonAdd.setPreferredSize(new java.awt.Dimension(71, 25));
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 90, -1));

        jButtonBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonBack.setText("<-- Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, -1));

        jLabelbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gold-cutlery-set-black-background_1220-4095.jpg"))); // NOI18N
        getContentPane().add(jLabelbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jLabelbackground.getAccessibleContext().setAccessibleName("Billing");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        InvoiceOfficer invoice;
        this.setVisible(false);
        new CancelOrder().setVisible(true);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        jTextFieldOrder.setText("");
        jTextFieldprice.setText("");
        jTextFieldquantity.setText("");
        jTextArea1.setText("");
        jTextFieldDay.setText("");
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        String order = jTextFieldOrder.getText();
        int quantity = Integer.parseInt(jTextFieldquantity.getText());
        double price = Double.parseDouble(jTextFieldprice.getText());
        String Day = jTextFieldDay.getText();
        printAtTextArea();

        try {
            JOptionPane.showMessageDialog(rootPane, "Add Success");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        jTextFieldOrder.setText("");
        jTextFieldprice.setText("");
        jTextFieldquantity.setText("");
        jTextFieldDay.setText("");
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jTextFieldOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOrderActionPerformed
        // TODO add your handling code here:
        InvoiceOfficer invoice = new InvoiceOfficer();
        if (jTextFieldOrder.getText().equals(invoice.getOrder())) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_jTextFieldOrderActionPerformed

    private void jTextFieldquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldquantityActionPerformed
        // TODO add your handling code here:
        InvoiceOfficer invoice = new InvoiceOfficer();
        if (jTextFieldquantity.getText().equals(invoice.getQuantity())) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_jTextFieldquantityActionPerformed

    private void jTextFieldpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldpriceActionPerformed
        // TODO add your handling code here:
        InvoiceOfficer invoice = new InvoiceOfficer();
        if (jTextFieldprice.getText().equals(invoice.getPrice())) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_jTextFieldpriceActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        GUIManager manage = new GUIManager();
        try {
            manage.iExitSystem();
        } catch (NumberFormatException e) {
            JOptionPane.showConfirmDialog(null, "Billing Error");
        }
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new EmployeeModule().setVisible(true);
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabelDay;
    private javax.swing.JLabel jLabelbackground;
    private javax.swing.JLabel jLabelorder;
    private javax.swing.JLabel jLabelprice;
    private javax.swing.JLabel jLabelquantity;
    private javax.swing.JLabel jLabeltitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldDay;
    private javax.swing.JTextField jTextFieldOrder;
    private javax.swing.JTextField jTextFieldprice;
    private javax.swing.JTextField jTextFieldquantity;
    // End of variables declaration//GEN-END:variables
}
